# Generated by Django 5.2.11 on 2026-02-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='formato',
            field=models.CharField(choices=[('vinilo', 'Vinilo'), ('cd', 'CD'), ('digital', 'Digital')], max_length=10),
        ),
    ]
