# Generated by Django 5.2.11 on 2026-02-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0002_producto_slug_alter_producto_formato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
